# Generated by Django 3.2.8 on 2022-08-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderitem_order_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gr', 'Group Buy'), ('mr', 'Merch')], default='mr', max_length=2),
        ),
    ]
